export const private_projects = [
  {
    id: "1",
    title: "The Planets",
    img: "https://hamzahfayad.github.io/portfolio/img/projects/planets.png",
    link: "https://hamzahfayad.github.io/planets-facts/",
    topic: ["All Projects", "HTML/SCSS/JS", "JSON"],
  },
  {
    id: "2",
    title: "Github Users",
    img: "https://hamzahfayad.github.io/portfolio/img/projects/devfinder.jpg",
    link: "https://hamzahfayad.github.io/devfinder/",
    topic: ["All Projects", "Vue.js", "API"],
  },
  {
    id: "3",
    title: "Weather App",
    img: "https://hamzahfayad.github.io/portfolio/img/projects/weather-app.png",
    link: "https://hamzahfayad.github.io/weather-app/",
    topic: ["All Projects", "Vue.js", "API"],
  },
  {
    id: "4",
    title: "Todo",
    img: "https://hamzahfayad.github.io/portfolio/img/projects/todo.png",
    link: "https://hamzahfayad.github.io/todo/",
    topic: ["All Projects", "Vue.js", "API"],
  },
  {
    id: "5",
    title: "Studio Ghibli",
    img: "https://hamzahfayad.github.io/portfolio/img/projects/studioghibli.JPG",
    link: "https://hamzahfayad.github.io/studioghibli/",
    topic: ["All Projects", "HTML/SCSS/JS"],
  },
  {
    id: "6",
    title: "Inpacs Messe",
    img: "/images/inpacs.png",
    topic: ["All Projects", "Wordpress"],
  },
  {
    id: "7",
    title: "Social Media Dashboard",
    img: "https://hamzahfayad.github.io/portfolio/img/projects/social-media-dashboard.jpg",
    link: "https://hamzahfayad.github.io/social-media-dashboard/",
    topic: ["All Projects", "HTML/SCSS/JS"],
  },
  {
    id: "8",
    title: "glow communication",
    img: "/images/glow.png",
    link: "http://dev-glow.glow-berlin.net/",
    topic: ["All Projects", "Wordpress"],
  },
];
